# Generated by Django 5.1.1 on 2026-09-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('public_key', models.CharField(max_length=64)),
                ('code_commit', models.CharField(default='unknown', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
